use_frameworks!

platform :ios, '9.0'

target 'TemplateScrolls_Example' do
  pod 'TemplateScrolls', :path => '../'
  
  pod 'Masonry'

  target 'TemplateScrolls_Tests' do
    inherit! :search_paths

    
  end
end
